# Generated by Django 2.1.5 on 2021-01-31 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('duration', models.CharField(max_length=255)),
                ('lecture_days', models.CharField(max_length=255)),
                ('start_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('end_time', models.TimeField(blank=True, verbose_name='Conversation Time')),
                ('course_img', models.ImageField(default='courses/static/courses/images/courses/default_course.jpg', null=True, upload_to='courses/static/courses/images/courses/')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.instructor_profile')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
