# Generated by Django 2.1.5 on 2021-02-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210204_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Accepted'), (2, 'Declined'), (3, 'Pending')], null=True),
        ),
    ]
