# Generated by Django 2.1.5 on 2021-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='saidatech_admin_profile',
            fields=[
                ('saidatech_admin_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'saidatech_admin',
            },
        ),
    ]
