# Generated by Django 2.1.5 on 2021-01-31 17:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a330efc-a5cf-45c3-b839-8514a0b2e46d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
