# Generated by Django 2.1.5 on 2021-02-02 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210202_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51592fcf-0213-4810-8206-b857c04de587'), editable=False, primary_key=True, serialize=False),
        ),
    ]
