# Generated by Django 2.1.5 on 2021-02-02 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210202_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29901f49-8167-4b5b-a8d6-62be9276174a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
