# Generated by Django 2.1.5 on 2021-02-05 01:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210204_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f3d3198f-223a-48d8-838f-474485f411ca'), editable=False, primary_key=True, serialize=False),
        ),
    ]
