# Generated by Django 2.1.5 on 2021-02-06 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210205_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5216e6a2-9d0a-4608-8770-fa36c9e3f21a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
