# Generated by Django 2.1.5 on 2021-02-06 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210206_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e98eb627-61bb-4527-8d49-2c97cbbc3713'), editable=False, primary_key=True, serialize=False),
        ),
    ]
