# Generated by Django 2.1.5 on 2021-02-06 20:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210206_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8b7ab774-5a9d-4537-b280-54389e0a655e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
