# Generated by Django 2.1.5 on 2021-02-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_profile',
            name='picture',
            field=models.ImageField(default='user_profile/static/courses/images/users/default_user.png', null=True, upload_to='user_profile/static/courses/images/users/'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='picture',
            field=models.ImageField(default='user_profile/static/courses/images/users/default_user.png', null=True, upload_to='user_profile/static/courses/images/users/'),
        ),
    ]
