# Generated by Django 2.1.5 on 2021-02-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210204_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor_profile',
            name='picture',
            field=models.ImageField(default='static/courses/images/users/default_user.png', null=True, upload_to='static/courses/images/users/'),
        ),
        migrations.AlterField(
            model_name='student_profile',
            name='picture',
            field=models.ImageField(default='static/courses/images/users/default_user.png', null=True, upload_to='static/courses/images/users/'),
        ),
    ]
