# Generated by Django 2.1.5 on 2021-02-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20210206_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='picture',
            field=models.ImageField(default='accounts/static/accounts/images/users/default_user.png', null=True, upload_to='accounts/static/accounts/images/users/'),
        ),
    ]
